code --install-extension adpyke.codesnap
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension brapifra.phpserver
code --install-extension burkeholland.simple-react-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.code-runner
code --install-extension jcbuisson.vue
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kiteco.kite
code --install-extension loilo.snazzy-light
code --install-extension naumovs.color-highlight
code --install-extension octref.vetur
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.vscode-graphql
code --install-extension suming.react-proptypes-generate
code --install-extension syler.sass-indented
code --install-extension sysoev.language-stylus
code --install-extension thisismanta.stylus-supremacy
code --install-extension tinkertrain.theme-panda
